name: puppet_code_manager

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: number

jobs:
  processing_release_manager:
    name: collecting_release_version
    runs-on: [ self-hosted, linux, release_manager ]
    steps:
    - id: step1
      name: Checking which files changed 
      run: |
        echo "Repo name is ${{ github.repository }} and the PR number is ${{ github.event.pull_request.number }}"
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL | jq -r '.[] | .filename')
               
        if [[ $FILES == 'release.txt' ]]
        then
          echo "Release.txt modified, procedding further to deploy the code on puppet master..."
          #echo "::set-output name=file_name::$(echo ${FILES})"
          echo "file_name=$FILES" >> $GITHUB_OUTPUT
          
          echo "Get the changes before we merge"
          org_repo_name=${{ github.repository }} 
          repo_name=$(echo ${org_repo_name} | cut -d/ -f2)
          
          cd ~/git
          if [[ -d ${repo_name} ]] ;  then rm -rf ${repo_name} ; fi
          
          gh auth login --with-token < ~/.gh_secrets
          
          echo "Cloing the repo"
          gh repo clone "https://github.com/${org_repo_name}"
          
          cd ${repo_name}
          echo "I am in ${repo_name}"
          
          echo "Checking out the PR"
          gh pr checkout ${{ github.event.pull_request.number }}
          changes=$(git diff -R main | grep ^+ | grep -v release.txt | sed 's/+//g')
          
          echo ${changes}
          #echo "::set-output name=changes_to_deploy::$(echo ${changes})"
          echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo ${changes_to_deploy}
          
        else 
          echo ""
          echo -e "\033[31;1;4mThis workflow designed to merge, changes in release.txt, found $FILES files with changes exiting....\033[0m"
          
          #echo "::set-output name=file_name::$(echo ${FILES})"
          echo "file_name=$FILES" >> $GITHUB_OUTPUT
          echo ""
        fi
    - id: step2
      name: PR Approval and Merging
      if: ${{ success() && steps.step1.outputs.file_name == 'release.txt' }} 
      run: |
        #Setting UP Variables#
        orgAndRepo=${{ inputs.repo_name }}
        orgName=$(echo $orgAndRepo | cut -d'/' -f1)
        repoName=$(echo $orgAndRepo | cut -d'/' -f2)
        
        echo "Printing Vars...."
        echo "Org Name - $orgName"
        echo "Repo Name - $repoName"
        
        #Execution Starts from here#
        cd ~/git
        if [ -d ${repoName} ]; then rm -rf ${repoName}; fi
        gh auth login --with-token < ~/.gh_secrets
        echo ""
        echo "Checking the status of GH login...."
        gh auth status
        echo ""
        
        echo "Clonning the repository...."
        gh repo clone "https://github.com/${{ inputs.repo_name }}"
        echo ""
        cd $repoName
        echo "I am in $repoName"
        echo ""
        echo "Checking out the PR...."
        gh pr checkout ${{ inputs.pr_number }}
        echo ""
        
        echo "Merging PR...."
        gh pr merge --merge
        if [ $? -ne 0 ]; then
          echo ""
          echo "PR Merger Failed!!"
          gh auth logout --hostname github.com
          echo ""
          exit 1
        else
          echo ""
          echo "PR Has Been Merged Successfully!!"
          gh auth logout --hostname github.com
        fi
    outputs:
      file_name: ${{ steps.step1.outputs.file_name }}
      changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
      
  processing_release_manager2:
    needs: processing_release_manager
    if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
    runs-on: [ self-hosted, linux, release_manager ]
    strategy:
      matrix:
        list_of_changes: ${{ fromJSON(needs.processing_release_manager.outputs.changes_from_pr) }}
    steps:
    - id: step3
      name: call actions
      if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
      uses: pcherukusfdc/release_manager@main
      with:
        repo_name: '${{ github.repository }}'
        pr_num: '${{ github.event.pull_request.number }}'
        #pr_changes: ${{ needs.processing_release_manager.outputs.changes_from_pr }}
        pr_changes: ${{ matrix.list_of_changes }}

